package:
  name: ros-noetic-lanelet2-routing
  version: 2.0.0
source:
  git_url: https://github.com/zzx9636/Lanelet2.git
  git_rev: tag_lanelet2_routing
  folder: ros-noetic-lanelet2-routing/src/work

build:
  script:
    sel(win): bld_catkin.bat
    sel(unix): build_catkin.sh
  number: 14
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - setuptools
    - sel(unix): make
    - sel(osx): tapi
    - sel(build_platform != target_platform): pkg-config
    - cmake
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): cython
    - sel(build_platform != target_platform): numpy
  host:
    - boost
    - gtest
    - numpy
    - pip
    - sel(build_platform == target_platform): pkg-config
    - python
    - ros-distro-mutex 0.3 noetic
    - ros-noetic-catkin
    - ros-noetic-lanelet2-core
    - ros-noetic-lanelet2-traffic-rules
    - ros-noetic-mrt-cmake-modules
  run:
    - boost
    - python
    - ros-distro-mutex 0.3 noetic
    - ros-noetic-lanelet2-core
    - ros-noetic-lanelet2-traffic-rules
    - ros-noetic-mrt-cmake-modules
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
